### ISSUE TITLE
Footer font and spacing to cater for responsive on Copyright text 

### ISSUE THREAD

**Issue by SarahHornsey** [Financial-Times/o-ft-footer#17]
![origami-footer](https://cloud.githubusercontent.com/assets/8235225/3995497/9f863298-2928-11e4-902d-3aaed0cc5185.png)

- Can the font size on the Copyright text be 11px for XL and M screens, and 9px for S screens.
- Can the Copy right text "FT and 'Financial Time' are trademarks of The Financial Times Ltd" lose the padding on the left of it.

**Comment by kaelig** [comment]
Fixed in latest beta
