### ISSUE TITLE
Copyright text adjusted for when a product removes links area

### ISSUE THREAD

**Issue by pauloneillft** [Financial-Times/o-ft-footer#18]
Vertical padding needed on copyright text for when a product removes the links area. 10px top and bottom
![screen shot 2014-08-22 at 12 24 24](https://cloud.githubusercontent.com/assets/3977053/4010113/ad95eb68-29ef-11e4-8385-6eaf6bb6eaf0.png)

**Comment by kaelig** [comment]
This was fixed in the latest beta.
