### ISSUE TITLE
o-ft-footer doesn't support silent mode

### ISSUE THREAD

**Issue by jamesnicholls** [Financial-Times/o-ft-footer#22]
o-ft-footer doesn't support silent mode. This can lead to redundant CSS if an app isn't using the footer link list.

**Comment by kaelig** [comment]
Thanks James for reporting this. I'll look into it when removing placeholder classes from the module.

**Comment by kaelig** [comment]
The links list is about 300 bytes gzipped, can we consider this to be an acceptable hit on performance? Otherwise we'll have to build a set of mixins enabling developers to cherry-pick what classes they want to use, and that seems overkill considering the small savings it would bring.

**Comment by jamesnicholls** [comment]
That's fine by me, as long as the module doesn't include fonts by default.

**Comment by kaelig** [comment]
Thanks. We're removing the dependency to o-fonts in other modules that were including `@font-face` declarations by mistake. Closing this as it will be solved with the new versions of the modules:

- o-quote
- o-hierarchical-nav
- o-promobox
- o-business-card
