### ISSUE TITLE
Add new optional section for navigation links

### ISSUE THREAD

**Issue by dan-searle** [Financial-Times/o-ft-footer#9]
For the [o-ft-header](https://github.com/Financial-Times/o-ft-header) core-experience, the navigation will consist of an HTML fragment link to a block of links at the foot of the page.

That block of links should perhaps be an optional section within this footer.

I believe @pauloneillft is producing a design for this.

**Comment by kaelig** [comment]
Since there's been no update in more than half a year, I'm closing this. If the need is still present, feel free to re-open.
